### ISSUE TITLE
Unable to evaluate model 

### ISSUE THREAD

**Issue by rajvijay68** [michiyasunaga/DrRepair#11]
```bash
DrRepair/evaluation/deepfix/out/code-compiler--2l-graph [master]
% for entry in ${test_split_root}/*
do
  probid=`basename $entry`
  python3 -u ../../test_deepfix.py \
  --input-code-dir ${program_data_root}/${probid}/erroneous \
  --repairer-server  http://0.0.0.0:8002/pred
done

Traceback (most recent call last):
  File "../../test_deepfix.py", line 331, in <module>
    main()
  File "../../test_deepfix.py", line 325, in main
    stitch()
  File "../../test_deepfix.py", line 290, in stitch
    stitch_helper(prog_fname)
  File "../../test_deepfix.py", line 231, in stitch_helper
    _code_str_tokenized = ' '.join(tokenize_code(_code, mod_brace=False))
DrRepair/utils/code_process.py", line 44, in tokenize_code
    clang.cindex.Config.set_library_path('/usr/local/Cellar/llvm/12.0.0/lib/')
  File "/Library/Python/3.8/lib/python/site-packages/clang/cindex.py", line 4107, in set_library_path
    raise Exception("library path must be set before before using " \
Exception: library path must be set before before using any other functionalities in libclang.
```

**Comment by rajvijay68** [comment]
Tried these, but didn't help 

```bash
export DYLD_LIBRARY_PATH=/usr/local/Cellar/llvm/12.0.0/lib/
export LD_LIBRARY_PATH=/usr/local/Cellar/llvm/12.0.0/lib/
```
